package com.dengpu.barbershop.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.is_member
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    private Boolean isMember;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.is_member
     *
     * @return the value of t_customer.is_member
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public Boolean getIsMember() {
        return isMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.is_member
     *
     * @param isMember the value for t_customer.is_member
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public void setIsMember(Boolean isMember) {
        this.isMember = isMember;
    }
}