package com.dengpu.barbershop.model;

public class HairDresser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hairdresser.id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hairdresser.name
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hairdresser.branch_id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    private Byte branchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hairdresser.id
     *
     * @return the value of t_hairdresser.id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hairdresser.id
     *
     * @param id the value for t_hairdresser.id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hairdresser.name
     *
     * @return the value of t_hairdresser.name
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hairdresser.name
     *
     * @param name the value for t_hairdresser.name
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hairdresser.branch_id
     *
     * @return the value of t_hairdresser.branch_id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public Byte getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hairdresser.branch_id
     *
     * @param branchId the value for t_hairdresser.branch_id
     *
     * @mbg.generated Wed Jan 17 16:14:47 CST 2018
     */
    public void setBranchId(Byte branchId) {
        this.branchId = branchId;
    }
}